// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlrMu78Q8k6enDe4oCCdm9Jbz8I6IjlHQ',
    appId: '1:718945631165:web:1e23f694c3e92a9d8070d4',
    messagingSenderId: '718945631165',
    projectId: 'pmsn2024-miguelruiz',
    authDomain: 'pmsn2024-miguelruiz.firebaseapp.com',
    storageBucket: 'pmsn2024-miguelruiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9shiZN85emGeO12s-ME4LKaROGS3e6xw',
    appId: '1:718945631165:android:0b3f2d23f52241c78070d4',
    messagingSenderId: '718945631165',
    projectId: 'pmsn2024-miguelruiz',
    storageBucket: 'pmsn2024-miguelruiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrB99FwYn72rVOTmnn_fqZl54bvsVSRU',
    appId: '1:718945631165:ios:5ce1062b1d8fa3578070d4',
    messagingSenderId: '718945631165',
    projectId: 'pmsn2024-miguelruiz',
    storageBucket: 'pmsn2024-miguelruiz.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );
}
